// Package envmaterializer implements Materializer by writing project.env and .env
// to the workspace's repo directory — matching the format that evidence/wt/webapi already read.
//
// project.env: non-secret, committable, written to <repo>/.talos/project.env
// .env: secrets, gitignored, written to <repo>/.env at mode 0600
package envmaterializer

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/John-Santa/talos/platform/workspaces/domain/workspace"
	"github.com/John-Santa/talos/platform/workspaces/port"
)

// WriteFileFn matches the signature of os.WriteFile for dependency injection in tests.
type WriteFileFn func(path string, data []byte, perm os.FileMode) error

// Materializer implements port.Materializer.
type Materializer struct {
	writeFile WriteFileFn
}

// New returns a Materializer that uses os.WriteFile.
func New() *Materializer {
	return &Materializer{writeFile: os.WriteFile}
}

// NewWithWriteFile returns a Materializer with an injected WriteFile function.
// Use in tests to avoid disk I/O.
func NewWithWriteFile(fn WriteFileFn) *Materializer {
	return &Materializer{writeFile: fn}
}

// Apply writes <repo>/.talos/project.env (non-secret) and <repo>/.env (secret, 0600).
// The produced files match the format that LoadInto/envfile already reads.
func (m *Materializer) Apply(_ context.Context, ws workspace.Workspace, c port.Credentials) error {
	// project.env — non-secret, committable
	talosDir := filepath.Join(ws.RepoPath, ".talos")
	if err := os.MkdirAll(talosDir, 0750); err != nil {
		return fmt.Errorf("creating .talos dir in %q: %w", ws.RepoPath, err)
	}
	projEnv := renderProjectEnv(ws)
	projEnvPath := filepath.Join(talosDir, "project.env")
	if err := m.writeFile(projEnvPath, []byte(projEnv), fs.FileMode(0644)); err != nil {
		return fmt.Errorf("writing project.env for %q: %w", ws.Name, err)
	}

	// .env — secrets, must be 0600
	secretEnv := renderSecretEnv(c)
	dotEnvPath := filepath.Join(ws.RepoPath, ".env")
	if err := m.writeFile(dotEnvPath, []byte(secretEnv), fs.FileMode(0600)); err != nil {
		return fmt.Errorf("writing .env for %q: %w", ws.Name, err)
	}

	return nil
}

// renderProjectEnv produces the non-secret project.env content.
// Format mirrors .talos/project.env as read by evidence/wt/webapi today.
func renderProjectEnv(ws workspace.Workspace) string {
	return fmt.Sprintf(
		"# .talos/project.env — generated by `ws use %s`. DO NOT add secrets here.\n"+
			"JIRA_SITE_URL=%s\n"+
			"JIRA_PROJECT_KEY=%s\n"+
			"JIRA_PROJECT_ID=%s\n",
		ws.Name,
		ws.Jira.SiteURL,
		ws.Jira.ProjectKey,
		ws.Jira.ProjectID,
	)
}

// renderSecretEnv produces the secret .env content (gitignored, 0600).
func renderSecretEnv(c port.Credentials) string {
	return fmt.Sprintf(
		"# .env — secrets managed by `ws`. gitignored, 0600.\n"+
			"JIRA_EMAIL=%s\n"+
			"JIRA_API_TOKEN=%s\n",
		c.Email,
		c.APIToken,
	)
}
